# Generated by Django 4.2.4 on 2023-08-28 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Toppings',
            new_name='Topping',
        ),
    ]
