# Generated by Django 4.2.4 on 2023-08-28 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzapi', '0002_rename_toppings_topping'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
